### ISSUE TITLE
关于本地部署和搜索的问题 似乎是CORS策略错误或者Elasticsearch的部署问题

### ISSUE THREAD

**Issue by Lokkue** [banned-historical-archives/banned-historical-archives.github.io#3978]
我在使用文章阅读 标签查找时没有问题 
但是当我使用搜索功能时 网页前端提示我无法localhost:3000从localhost:9200获取资源 
提示时CORS头部缺失 没有提供 “Access-Control-Allow-Origin”头部
我不确定这是否只是前端的问题，如果不是请提醒我增加后端的日志（顺便告诉我我如何获取日志）

另外我希望你们能重新考察一下部署文档的问题。。。在我的实际操作中遇到的问题似乎都是没有针对用户环境做改进，希望你们能够改进本地部署的问题，为非精通技术的人员提供为备份文库出一份力的条件

**Comment by banned-historical-archives** [comment]
应该是刚才的修改没有生效

"http.cors.allow-origin='*' "

**Comment by banned-historical-archives** [comment]
我有时间在windows上部署看看

**Comment by banned-historical-archives** [comment]
"http.cors.allow-origin=\"*\""

你试试这样行不行

**Comment by banned-historical-archives** [comment]
-e "http.cors.allow-origin=*"

**Comment by Lokkue** [comment]
> -e "http.cors.allow-origin=*"

试了一下这个，在docker上启动es01会马上闪退 要建立索引时会提示无法链接到elasticsearch

**Comment by Lokkue** [comment]
> ```
> "http.cors.allow-origin=\"*\""
> ```
> 
> 你试试这样行不行

这个是格式错误

**Comment by banned-historical-archives** [comment]
试试把环境变量存在env_file里面
```
http.cors.allow-origin=*
aaa=bbb
...
```

docker run --env-file=env_file ...

**Comment by Lokkue** [comment]
我使用了命令
```
 docker run -d --name es01 -p 9200:9200 -p 9300:9300 --env-file "../en/en.txt" -it docker.elastic.co/elasticsearch/elasticsearch:8.5.1
```
其中环境变量的文件的内容是
```
http.cors.enabled=true
http.cors.allow-origin=*
xpack.security.authc.anonymous.username=anonymous_user
xpack.security.authc.anonnymous.authz_exceptioin=true
xpack.security.authc.anonymous.roles=superuser
ELASTIC_USERNAME=elastic
ELASTIC_PASSWORD=password
discovery.type=single-node
```
仍然出现了es01闪退的情况
这是docker内的日志
```
2024-05-01 10:54:38 Exception in thread "main" org.elasticsearch.common.settings.SettingsException: Failed to load settings from [overrides.yml]
2024-05-01 10:54:38 at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:1231)
2024-05-01 10:54:38 at org.elasticsearch.node.InternalSettingsPreparer.loadOverrides(InternalSettingsPreparer.java:143)
2024-05-01 10:54:38 at org.elasticsearch.node.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:53)
2024-05-01 10:54:38 at org.elasticsearch.common.cli.EnvironmentAwareCommand.createEnv(EnvironmentAwareCommand.java:110)
2024-05-01 10:54:38 at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:54)
2024-05-01 10:54:38 at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
2024-05-01 10:54:38 at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:94)
2024-05-01 10:54:38 at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
2024-05-01 10:54:38 at org.elasticsearch.cli.Command.main(Command.java:50)
2024-05-01 10:54:38 at org.elasticsearch.launcher.CliToolLauncher.main(CliToolLauncher.java:64)
2024-05-01 10:54:38 Caused by: org.elasticsearch.xcontent.XContentParseException: [2:23] while scanning an alias
2024-05-01 10:54:38  in 'reader', line 2, column 25:
2024-05-01 10:54:38     http.cors.allow-origin: *
2024-05-01 10:54:38                             ^
2024-05-01 10:54:38 unexpected character found 
2024-05-01 10:54:38 (10)
2024-05-01 10:54:38  in 'reader', line 2, column 26:
2024-05-01 10:54:38     http.cors.allow-origin: *
2024-05-01 10:54:38                              ^
2024-05-01 10:54:38 
2024-05-01 10:54:38  at [Source: (ByteArrayInputStream); line: 2, column: 23]
2024-05-01 10:54:38 at org.elasticsearch.xcontent.provider.json.JsonXContentParser.newXContentParseException(JsonXContentParser.java:52)
2024-05-01 10:54:38 at org.elasticsearch.xcontent.provider.json.JsonXContentParser.nextToken(JsonXContentParser.java:62)
2024-05-01 10:54:38 at org.elasticsearch.common.settings.Settings.fromXContent(Settings.java:759)
2024-05-01 10:54:38 at org.elasticsearch.common.settings.Settings.fromXContent(Settings.java:724)
2024-05-01 10:54:38 at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:1227)
2024-05-01 10:54:38 ... 9 more
2024-05-01 10:54:38 Caused by: com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException: while scanning an alias
2024-05-01 10:54:38  in 'reader', line 2, column 25:
2024-05-01 10:54:38     http.cors.allow-origin: *
2024-05-01 10:54:38                             ^
2024-05-01 10:54:38 unexpected character found 
2024-05-01 10:54:38 (10)
2024-05-01 10:54:38  in 'reader', line 2, column 26:
2024-05-01 10:54:38     http.cors.allow-origin: *
2024-05-01 10:54:38                              ^
2024-05-01 10:54:38 
2024-05-01 10:54:38  at [Source: (ByteArrayInputStream); line: 2, column: 23]
2024-05-01 10:54:38 at com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException.from(MarkedYAMLException.java:28)
2024-05-01 10:54:38 at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:407)
2024-05-01 10:54:38 at org.elasticsearch.xcontent.provider.json.JsonXContentParser.nextToken(JsonXContentParser.java:58)
2024-05-01 10:54:38 ... 12 more
2024-05-01 10:54:38 Caused by: while scanning an alias
2024-05-01 10:54:38  in 'reader', line 2, column 25:
2024-05-01 10:54:38     http.cors.allow-origin: *
2024-05-01 10:54:38                             ^
2024-05-01 10:54:38 unexpected character found 
2024-05-01 10:54:38 (10)
2024-05-01 10:54:38  in 'reader', line 2, column 26:
2024-05-01 10:54:38     http.cors.allow-origin: *
2024-05-01 10:54:38                              ^
2024-05-01 10:54:38 
2024-05-01 10:54:38 at org.yaml.snakeyaml.scanner.ScannerImpl.scanAnchor(ScannerImpl.java:1523)
2024-05-01 10:54:38 at org.yaml.snakeyaml.scanner.ScannerImpl.fetchAlias(ScannerImpl.java:972)
2024-05-01 10:54:38 at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:422)
2024-05-01 10:54:38 at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:263)
2024-05-01 10:54:38 at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:694)
2024-05-01 10:54:38 at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:185)
2024-05-01 10:54:38 at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:195)
2024-05-01 10:54:38 at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:403)
2024-05-01 10:54:38 ... 13 more
```
值得一提的是：我把文件中的变量改成 http.cors.allow-origin="*"后elasticsearch能够正常运行
但是我在执行搜索时仍然遇到开始的错误

**Comment by banned-historical-archives** [comment]
="*"
试试

**Comment by Lokkue** [comment]
> ="*" 试试

这个成功了但是在我试图创建索引时，elasticsearch拒绝链接，理由似乎是通过https通道访问了http请求，我需要修改什么

**Comment by banned-historical-archives** [comment]
-e "xpack.security.http.ssl.enabled=false" 
漏了一个

**Comment by Lokkue** [comment]
好的能够搜索了，感谢同志的技术支持
